TCMR_DB_DIR: 'F:/tcmr_data/TCMR_data_RELEASE/train'
AMASS_DIR: 'data/amass'
INSTA_DIR: 'data/insta_variety'
MPII3D_DIR: 'data/mpi_inf_3dhp'
THREEDPW_DIR: 'data/3dpw'
H36M_DIR: 'data/h36m'
PENNACTION_DIR: 'data/penn_action'
POSETRACK_DIR: 'data/posetrack'
BASE_DATA_DIR: 'data/base_data'